// 集中管理所有前端路由路径。
// 独立成模块是为了让它在生产构建中能被 vite-plugin-javascript-obfuscator 重度混淆，
// 从而把页面 / 后台 / 管理端等 URL 路径字符串加密隐藏，避免 App.tsx 的路由表被静态逆向直接看穿。
// 注意：App.tsx 本身因含 React.lazy 动态 import 不参与混淆，此处路径字符串即架构的最后暴露面。
export const ROUTES = {
  appeal: '/appeal',
  securityPolicy: '/security-policy',
  adminAppeals: '/admin/appeals',
  privacyAgreement: '/privacy-agreement',
  auth: '/auth',
  adminLogin: '/admin-login',
  bugReport: '/bug-report',
  privacy: '/privacy',
  terms: '/terms',
  forgotPassword: '/forgot-password',
  home: '/',
  courses: '/courses',
  learn: '/learn/:type',
  progress: '/progress',
  community: '/community',
  achievements: '/achievements',
  daily: '/daily',
  battle: '/battle',
  profile: '/profile',
  settings: '/settings',
  groups: '/groups',
  messages: '/messages',
  vocabTest: '/vocab-test',
  bugHistory: '/bug-history',
  notifications: '/notifications',
  admin: '/admin',
  adminServices: '/admin/services',
  adminCreateAdmin: '/admin/create-admin',
  adminSecurity: '/admin/security',
  adminSecurityDefense: '/admin/security-defense',
  aiAssistant: '/ai-assistant',
  srsReview: '/srs-review',
  voicePractice: '/voice-practice',
  leaderboard: '/leaderboard',
  planner: '/planner',
  readingWriting: '/reading-writing',
  social: '/social',
  learningStats: '/learning-stats',
  security: '/security',
  privacySettings: '/privacy-settings',
  notificationSettings: '/notification-settings',
  aiAgent: '/ai-agent',
  surveys: '/surveys',
  adminSurveys: '/admin/surveys',
  securityCenter: '/security-center',
  membership: '/membership',
  aiTutorDemo: '/ai-tutor-demo',
}

export const ROUTES_WILDCARD = '*'